<a href="https://colab.research.google.com/github/zeeshan3106/Machine-Learning/blob/main/Gradient_Boost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [195]:
import pandas as pd
data = pd.read_csv("australian_property_regression.csv")
data
X = data[['Distance_to_CBD_KM','Floor_Area_SqM','Bedroom_Count','Property_Value_AUD_K']]
data
y = data['Property_Value_AUD_K']
X['pred_1'] = X['Property_Value_AUD_K'].mean()
X

/tmp/ipykernel_2350/144627171.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['pred_1'] = X['Property_Value_AUD_K'].mean()

,Distance_to_CBD_KM,Floor_Area_SqM,Bedroom_Count,Property_Value_AUD_K,pred_1
0,10.3,59.0,2,665.3,1082.304
1,23.8,241.0,3,1152.6,1082.304
2,18.7,144.0,4,916.3,1082.304
3,15.6,203.0,2,998.5,1082.304
4,5.2,322.0,2,1579.5,1082.304
...,...,...,...,...,...
95,13.1,155.0,3,954.2,1082.304
96,13.8,268.0,3,1293.0,1082.304
97,11.5,319.0,1,1374.6,1082.304
98,2.1,316.0,3,1548.7,1082.304
99,4.0,284.0,3,1475.7,1082.304

In [196]:
X.sample(2)

,Distance_to_CBD_KM,Floor_Area_SqM,Bedroom_Count,Property_Value_AUD_K,pred_1
73,20.7,118.0,2,751.0,1082.304
71,6.2,55.0,3,792.0,1082.304

In [197]:
X['pred_1'] = X['Property_Value_AUD_K'].mean()
y = X['pred_1']

X['Loss_1'] = X['Property_Value_AUD_K'] - X['pred_1']
X.sample(2)
X2 = X[['Distance_to_CBD_KM','Floor_Area_SqM','Bedroom_Count']]
X2
y2 = X['Loss_1']
y2

/tmp/ipykernel_2350/3320678542.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['pred_1'] = X['Property_Value_AUD_K'].mean()

0    -417.004
1      70.296
2    -166.004
3     -83.804
4     497.196
       ...
95   -128.104
96    210.696
97    292.296
98    466.396
99    393.396
Name: Loss_1, Length: 100, dtype: float64

In [198]:
from sklearn.tree import DecisionTreeRegressor
tree = DecisionTreeRegressor(max_leaf_nodes=8)
training = tree.fit(X2,y2)
pred = tree.predict(X2)
pred2 = pd.DataFrame(pred)
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y2, pred)
X2['Loss_1']= X['Loss_1']
X2['pred_2'] = pred2

X2['Loss_2']=X2['Loss_1']-X2['pred_2']
X2

/tmp/ipykernel_2350/4104876679.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X2['Loss_1']= X['Loss_1']
/tmp/ipykernel_2350/4104876679.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X2['pred_2'] = pred2

,Distance_to_CBD_KM,Floor_Area_SqM,Bedroom_Count,Loss_1,pred_2,Loss_2
0,10.3,59.0,2,-417.004,-377.592889,-39.411111
1,23.8,241.0,3,70.296,-89.379000,159.675000
2,18.7,144.0,4,-166.004,-255.792235,89.788235
3,15.6,203.0,2,-83.804,109.568222,-193.372222
4,5.2,322.0,2,497.196,406.380211,90.815789
...,...,...,...,...,...,...
95,13.1,155.0,3,-128.104,-255.792235,127.688235
96,13.8,268.0,3,210.696,255.659636,-44.963636
97,11.5,319.0,1,292.296,406.380211,-114.084211
98,2.1,316.0,3,466.396,406.380211,60.015789
99,4.0,284.0,3,393.396,406.380211,-12.984211

In [199]:
X3 = X2[['Distance_to_CBD_KM','Floor_Area_SqM','Bedroom_Count']]
X3
y3 = X2['Loss_2']
y3

0     -39.411111
1     159.675000
2      89.788235
3    -193.372222
4      90.815789
         ...
95    127.688235
96    -44.963636
97   -114.084211
98     60.015789
99    -12.984211
Name: Loss_2, Length: 100, dtype: float64

In [203]:
from sklearn.tree import DecisionTreeRegressor
tree = DecisionTreeRegressor(max_leaf_nodes=32)
training = tree.fit(X3,y3)
pred = tree.predict(X3)
pred3 = pd.DataFrame(pred)
# from sklearn.metrics import mean_absolute_error
# mean_absolute_error(y2, pred3)
pred3
X3['Loss_3']= X2['Loss_2']
X3['pred_3'] = pred3
X3

/tmp/ipykernel_2350/2102961034.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X3['Loss_3']= X2['Loss_2']
/tmp/ipykernel_2350/2102961034.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X3['pred_3'] = pred3

    Distance_to_CBD_KM  Floor_Area_SqM  Bedroom_Count      Loss_3      pred_3
0                 10.3            59.0              2  -39.411111  -75.005625
1                 23.8           241.0              3  159.675000   79.671959
2                 18.7           144.0              4   89.788235   57.313242
3                 15.6           203.0              2 -193.372222 -193.372222
4                  5.2           322.0              2   90.815789   67.077339
..                 ...             ...            ...         ...         ...
95                13.1           155.0              3  127.688235  127.688235
96                13.8           268.0              3  -44.963636  -57.373477
97                11.5           319.0              1 -114.084211  -75.005625
98                 2.1           316.0              3   60.015789   65.404094
99                 4.0           284.0              3  -12.984211  -36.479288

[100 rows x 5 columns]

In [201]:
Combine = 1082+(406.380211)+(65.404094)
Final={}
Final=  pd.DataFrame([Combine],columns=['Combined_Prediction'])

Final['Actual_Price']=1548.7
Final

   Combined_Prediction  Actual_Price
0          1553.784305        1548.7