<a href="https://colab.research.google.com/github/zeeshan3106/Machine-Learning/blob/main/K_Nearest_Neighbour_(KNN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import pandas as pd
data = pd.read_csv("Aus_migration.csv")
data.head()

,Age,CountryOfOrigin,EducationLevel,Occupation,YearsOfExperience,EnglishTestScore,PointsScore,VisaType,DestCity,YearlyIncome_AUD,VisaApproved
0,28,China,Bachelor Degree,Accountant,6,85,140,Skilled Independent (Subclass 189),Melbourne,89841,1
1,39,Philippines,Bachelor Degree,Registered Nurse,7,76,115,Skilled Nominated (Subclass 190),Melbourne,78436,0
2,28,India,Master Degree,Chef,8,80,145,Skilled Independent (Subclass 189),Melbourne,72810,1
3,40,Philippines,Master Degree,Chef,2,74,105,Temporary Graduate (Subclass 485),Melbourne,116240,0
4,30,Philippines,Advanced Diploma,Accountant,6,77,125,Employer Nomination Scheme (Subclass 186),Melbourne,80592,0

In [42]:
X = data.drop('VisaApproved',axis=1)
y = data['VisaApproved']
from sklearn.model_selection import train_test_split

X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.2, random_state = 42)
X_train.sample(2)

,Age,CountryOfOrigin,EducationLevel,Occupation,YearsOfExperience,EnglishTestScore,PointsScore,VisaType,DestCity,YearlyIncome_AUD
37,28,Philippines,Advanced Diploma,Accountant,5,88,135,Skilled Independent (Subclass 189),Melbourne,126843
16,18,United Kingdom,Master Degree,Registered Nurse,1,66,115,Student Visa (Subclass 500),Melbourne,26264

In [46]:
from sklearn.preprocessing import OrdinalEncoder
ordinal = OrdinalEncoder()
X_train_transform = ordinal.fit_transform(X_train)
X_test_transform = ordinal.fit_transform(X_test)
pd.DataFrame(X_train_transform)

       0    1    2    3     4     5    6    7    8     9
0   12.0  0.0  2.0  2.0   0.0   7.0  5.0  3.0  0.0  14.0
1    3.0  2.0  3.0  5.0   9.0  12.0  6.0  1.0  0.0  79.0
2   13.0  0.0  3.0  5.0   2.0   2.0  4.0  1.0  0.0  33.0
3    0.0  0.0  1.0  3.0  11.0   9.0  6.0  4.0  0.0  70.0
4    5.0  3.0  3.0  4.0   6.0  16.0  7.0  4.0  0.0  24.0
..   ...  ...  ...  ...   ...   ...  ...  ...  ...   ...
75  13.0  4.0  1.0  3.0   0.0   4.0  4.0  3.0  0.0  15.0
76  18.0  3.0  0.0  0.0   8.0   0.0  3.0  2.0  0.0  53.0
77   4.0  4.0  0.0  2.0  11.0   1.0  5.0  0.0  0.0  68.0
78   8.0  5.0  3.0  4.0   2.0  21.0  6.0  0.0  0.0  55.0
79  12.0  3.0  1.0  2.0   5.0   4.0  6.0  4.0  0.0  74.0

[80 rows x 10 columns]

In [47]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_transform_scale = scaler.fit_transform(X_train_transform)
X_train_test_scale = scaler.fit_transform(X_test_transform)
pd.DataFrame(X_train_transform_scale)

,0,1,2,3,4,5,6,7,8,9
0,0.427189,-1.545623,0.380637,-0.236866,-1.425539,-0.454759,-0.165203,0.749194,0.0,-1.104269
1,-1.519496,-0.368005,1.250665,1.435131,1.192798,0.261397,0.324288,-0.768161,0.0,1.710534
2,0.643488,-1.545623,1.250665,1.435131,-0.843687,-1.170915,-0.654695,-0.768161,0.0,-0.281480
3,-2.168391,-1.545623,-0.489391,0.320466,1.774651,-0.168297,0.324288,1.507871,0.0,1.320792
4,-1.086899,0.220803,1.250665,0.877798,0.320019,0.834322,0.813779,1.507871,0.0,-0.671222
...,...,...,...,...,...,...,...,...,...,...
75,0.643488,0.809612,-0.489391,0.320466,-1.425539,-0.884453,-0.654695,0.749194,0.0,-1.060964
76,1.724980,0.220803,-1.359419,-1.351531,0.901872,-1.457378,-1.144186,-0.009483,0.0,0.584613
77,-1.303198,0.809612,-1.359419,-0.236866,1.774651,-1.314147,-0.165203,-1.526838,0.0,1.234183
78,-0.438004,1.398420,1.250665,0.877798,-0.843687,1.550478,0.324288,-1.526838,0.0,0.671222
79,0.427189,0.220803,-0.489391,-0.236866,0.029093,-0.884453,0.324288,1.507871,0.0,1.494011

In [85]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train_transform_scale, y_train)
knnpred = knn.predict(X_train_test_scale)

knnpred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0])

In [84]:
from sklearn.metrics import accuracy_score
accuracy_score(knnpred, y_test)*100

80.0

In [65]:
import numpy as np
np.sqrt(X_train_transform.shape[0])

np.float64(8.94427190999916)