<a href="https://colab.research.google.com/github/zeeshan3106/Machine-Learning/blob/main/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = pd.read_csv("tennis_playing_records.csv")
data.head(1)

  Outlook Temperature Humidity    Wind PlayTennis
0    Rain         Hot     High  Strong         No

**`Applying Naive Bayes `**

In [ ]:
out = data['Outlook'].value_counts()
temp = data['Temperature'].value_counts()
hum = data['Humidity'].value_counts()
wind = data['Wind'].value_counts()
print(out,"\n",temp,"\n",hum,"\n",wind)

Outlook
Sunny       37
Rain        35
Overcast    28
Name: count, dtype: int64
 Temperature
Hot     43
Cool    33
Mild    24
Name: count, dtype: int64
 Humidity
Normal    53
High      47
Name: count, dtype: int64
 Wind
Weak      58
Strong    42
Name: count, dtype: int64

In [ ]:
outlook = pd.crosstab(data['Outlook'],data['PlayTennis'])
outlook

PlayTennis  No  Yes
Outlook
Overcast     0   28
Rain        17   18
Sunny       16   21

In [ ]:
overcno= outlook .iloc[0,0]/outlook .iloc[:,0].sum()

rainno = outlook .iloc[1,0]/outlook .iloc[:,0].sum()

Sunnyno = outlook .iloc[2,0]/outlook .iloc[:,0].sum()


overcyes = outlook .iloc[0,1]/outlook .iloc[:,1].sum()

rainyes = outlook .iloc[1,1]/outlook .iloc[:,1].sum()
rainyes
Sunnyyes = outlook .iloc[2,1]/outlook .iloc[:,1].sum()

In [ ]:
temp = pd.crosstab(data['Temperature'],data['PlayTennis'])
temp

PlayTennis   No  Yes
Temperature
Cool         12   21
Hot          13   30
Mild          8   16

In [ ]:
tmpcolno = temp.iloc[0,0]/temp.iloc[:,0].sum()
tmpcolno
tmphotno = temp.iloc[1,0]/temp.iloc[:,0].sum()
tmphotno
tmpmildno = temp.iloc[2,0]/temp.iloc[:,0].sum()
tmpmildno

tmpcolyes = temp.iloc[0,1]/temp.iloc[:,1].sum()
tmpcolyes
tmphotyes = temp.iloc[1,1]/temp.iloc[:,1].sum()
tmphotyes
tmpmildyes = temp.iloc[2,1]/temp.iloc[:,1].sum()
tmpmildyes

np.float64(0.23880597014925373)

In [ ]:
hum = pd.crosstab(data['Humidity'],data['PlayTennis'])
hum

PlayTennis  No  Yes
Humidity
High        25   22
Normal       8   45

In [101]:
humhighno = hum.iloc[0,0]/hum.iloc[:,0].sum()
humhighno
humhighyes = hum.iloc[1,0]/hum.iloc[:,1].sum()
humhighyes

humnormalo = hum.iloc[0,0]/hum.iloc[:,0].sum()
humnormalo
humnormalyes = hum.iloc[1,0]/hum.iloc[:,1].sum()
humnormalyes

np.float64(0.11940298507462686)

In [ ]:
wind = pd.crosstab(data['Wind'],data['PlayTennis'])
wind

PlayTennis  No  Yes
Wind
Strong      24   18
Weak         9   49

In [102]:
WindStrongno = wind.iloc[0,0]/wind.iloc[:,0].sum()
WindStrongno
WindStrongYes = wind.iloc[1,0]/wind.iloc[:,1].sum()
WindStrongYes
Windweekno = wind.iloc[0,0]/wind.iloc[:,0].sum()
WindStrongno
WindweekYes = wind.iloc[1,0]/wind.iloc[:,1].sum()
WindStrongYes

np.float64(0.13432835820895522)

In [103]:
p = data['PlayTennis'].value_counts()
py = p['Yes']
py
pn= p['No']

In [111]:
pyes = py*Sunnyyes*tmphotyes*humhighyes*WindStrongYes
pyes

np.float64(0.15081642356273878)

In [112]:
pno = pn*Sunnyno*tmphotno*humhighno*WindStrongno
pno

np.float64(3.4727439686117374)

Normalizing

In [137]:
pyespercentage = pyes/(pyes+pno)
pyespercentage = pyespercentage*100
pnopercentage = pno/(pyes+pno)
pnopercentage = pnopercentage*100
if (pyespercentage>pnopercentage):
  print(pyespercentage,"%","\n","yes there would definiately a wonderful Match")
else:
  print(pnopercentage,"%","\n","No Match In these Conditions.")

95.83789402576413 %
 No Match In these Conditions.