<a href="https://colab.research.google.com/github/zeeshan3106/Machine-Learning/blob/main/Naive_Bayes%20Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
import pandas as pd
data = pd.read_csv("tennis_match_winners_categorical.csv")
data = data.fillna(method="ffill")
data
Surface = pd.crosstab(data['Surface'],data['Match_Winner'])
Surface
claydjoick = Surface.iloc[0,0]/Surface.iloc[:,0].sum()
harddjoick = Surface.iloc[1,0]/Surface.iloc[:,1].sum()
grassdjoick = Surface.iloc[2,0]/Surface.iloc[:,2].sum()


claynadal = Surface.iloc[0,1]/Surface.iloc[:,0].sum()
hardnadal = Surface.iloc[1,1]/Surface.iloc[:,1].sum()
grassnadal = Surface.iloc[2,1]/Surface.iloc[:,2].sum()

claysinner = Surface.iloc[0,2]/Surface.iloc[:,0].sum()
hardsinner = Surface.iloc[1,2]/Surface.iloc[:,1].sum()
grasssinner = Surface.iloc[2,2]/Surface.iloc[:,2].sum()

/tmp/ipykernel_552/3147572354.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data = data.fillna(method="ffill")

In [50]:
data
Weather = pd.crosstab(data['Weather'],data['Match_Winner'])
Weather

djoko_total  = Weather.iloc[:, 0].sum()
nadal_total  = Weather.iloc[:, 1].sum()
sinner_total = Weather.iloc[:, 2].sum()

humid_djoko    = Weather.iloc[0, 0] / djoko_total
overcast_djoko = Weather.iloc[1, 0] / djoko_total
rainy_djoko    = Weather.iloc[2, 0] / djoko_total
sunny_djoko    = Weather.iloc[3, 0] / djoko_total

humid_nadal    = Weather.iloc[0, 1] / nadal_total
overcast_nadal = Weather.iloc[1, 1] / nadal_total
rainy_nadal    = Weather.iloc[2, 1] / nadal_total
sunny_nadal    = Weather.iloc[3, 1] / nadal_total


humid_sinner    = Weather.iloc[0, 2] / sinner_total
overcast_sinner = Weather.iloc[1, 2] / sinner_total
rainy_sinner    = Weather.iloc[2, 2] / sinner_total
sunny_sinner    = Weather.iloc[3, 2] / sinner_total

In [51]:
data
Match_Winner = pd.crosstab(data['Humidity'],data['Match_Winner'])

djoko_total  = Match_Winner.iloc[:, 0].sum()
nadal_total  = Match_Winner.iloc[:, 1].sum()
sinner_total = Match_Winner.iloc[:, 2].sum()


high_djoko   = Match_Winner.iloc[0, 0] / djoko_total
low_djoko    = Match_Winner.iloc[1, 0] / djoko_total
medium_djoko = Match_Winner.iloc[2, 0] / djoko_total


high_nadal   = Match_Winner.iloc[0, 1] / nadal_total
low_nadal    = Match_Winner.iloc[1, 1] / nadal_total
medium_nadal = Match_Winner.iloc[2, 1] / nadal_total

high_sinner   = Match_Winner.iloc[0, 2] / sinner_total
low_sinner    = Match_Winner.iloc[1, 2] / sinner_total
medium_sinner = Match_Winner.iloc[2, 2] / sinner_total

In [52]:
Wind_Speed= pd.crosstab(data['Wind_Speed'],data['Match_Winner'])
Wind_Speed
djoko_total  = Wind_Speed.iloc[:, 0].sum()
nadal_total  = Wind_Speed.iloc[:, 1].sum()
sinner_total = Wind_Speed.iloc[:, 2].sum()

breezy_djoko = Wind_Speed.iloc[0, 0] / djoko_total
calm_djoko   = Wind_Speed.iloc[1, 0] / nadal_total
gale_djoko   = Wind_Speed.iloc[2, 0] / djoko_total

breezy_nadal = Wind_Speed.iloc[0, 1] / nadal_total
calm_nadal   = Wind_Speed.iloc[1, 1] / nadal_total
gale_nadal   = Wind_Speed.iloc[2, 1] / nadal_total

breezy_sinner = Wind_Speed.iloc[0, 2] / sinner_total
calm_sinner   = Wind_Speed.iloc[1, 2] / sinner_total
gale_sinner   = Wind_Speed.iloc[2, 2] / sinner_total

In [53]:
Time_Of_Day = pd.crosstab(data['Time_Of_Day'],data['Match_Winner'])
Time_Of_Day
djoko_total  = Time_Of_Day.iloc[:, 0].sum()
nadal_total  = Time_Of_Day.iloc[:, 1].sum()
sinner_total = Time_Of_Day.iloc[:, 2].sum()

day_djoko   = Time_Of_Day.iloc[0, 0] / djoko_total
night_djoko = Time_Of_Day.iloc[1, 0] / djoko_total

day_nadal   = Time_Of_Day.iloc[0, 1] / nadal_total
night_nadal = Time_Of_Day.iloc[1, 1] / nadal_total

day_sinner   = Time_Of_Day.iloc[0, 2] / sinner_total
night_sinner = Time_Of_Day.iloc[1, 2] / sinner_total

In [70]:
Crowd_Favor = pd.crosstab(data['Crowd_Favor'],data['Match_Winner'])
Crowd_Favor

djoko_total  = Crowd_Favor.iloc[:, 0].sum()
nadal_total  = Crowd_Favor.iloc[:, 1].sum()
sinner_total = Crowd_Favor.iloc[:, 2].sum()

favor_djoko   = Crowd_Favor.iloc[0, 0] / djoko_total
against_djoko = Crowd_Favor.iloc[1, 0] / djoko_total
neutral_djoko = Crowd_Favor.iloc[2, 0] / djoko_total

against_nadal  = Crowd_Favor.iloc[0, 1] / nadal_total
favour_nadal = Crowd_Favor.iloc[1, 1] / nadal_total
neutral_nadal = Crowd_Favor.iloc[2, 1] / nadal_total

against_sinner   = Crowd_Favor.iloc[0, 2] / sinner_total
neutral_sinner = Crowd_Favor.iloc[1, 2] / sinner_total
favour_sinner = Crowd_Favor.iloc[2, 2] / sinner_total

Crowd_Favor

Match_Winner  Djokovic  Nadal  Sinner
Crowd_Favor
Djokovic            16     10       1
Nadal               14     16      13
Sinner               7     10      13

In [71]:
Tournament_Stage = pd.crosstab(data['Tournament_Stage'],data['Match_Winner'])
Tournament_Stage
djoko_total  = Tournament_Stage.iloc[:, 0].sum()
nadal_total  = Tournament_Stage.iloc[:, 1].sum()
sinner_total = Tournament_Stage.iloc[:, 2].sum()

final_djoko = Tournament_Stage.iloc[0, 0] / djoko_total
qf_djoko    = Tournament_Stage.iloc[1, 0] / djoko_total
sf_djoko    = Tournament_Stage.iloc[2, 0] / djoko_total

final_nadal = Tournament_Stage.iloc[0, 1] / nadal_total
qf_nadal    = Tournament_Stage.iloc[1, 1] / nadal_total
sf_nadal    = Tournament_Stage.iloc[2, 1] / nadal_total

final_sinner = Tournament_Stage.iloc[0, 2] / sinner_total
qf_sinner    = Tournament_Stage.iloc[1, 2] / sinner_total
sf_sinner    = Tournament_Stage.iloc[2, 2] / sinner_total
Tournament_Stage

Match_Winner      Djokovic  Nadal  Sinner
Tournament_Stage
Final                   11     10      11
Quarter-Final           12     17      12
Semi-Final              14      9       4

In [117]:
data['Match_Winner'].value_counts()
Djokovicyes = data['Match_Winner'].value_counts()[0]
Nadalyes = data['Match_Winner'].value_counts()[1]
sinneryes = data['Match_Winner'].value_counts()[2]
DjovikNo = data['Match_Winner'].value_counts()[1]+data['Match_Winner'].value_counts()[2]
NadalNo = data['Match_Winner'].value_counts()[0]+data['Match_Winner'].value_counts()[2]
SinnerNo = data['Match_Winner'].value_counts()[0]+data['Match_Winner'].value_counts()[1]

/tmp/ipykernel_552/2667905393.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Djokovicyes = data['Match_Winner'].value_counts()[0]
/tmp/ipykernel_552/2667905393.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Nadalyes = data['Match_Winner'].value_counts()[1]
/tmp/ipykernel_552/2667905393.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sinneryes = data['Match_Winner'].value_counts()[2]
/tmp/ipykernel_552/2667905393.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  DjovikNo = data['Match_Winner'].value_counts()[1]+data['Match_Winner'].value_counts()[2]
/tmp/ipykernel_552/2667905393.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  DjovikNo = data['Match_Winner'].value_counts()[1]+data['Match_Winner'].value_counts()[2]
/tmp/ipykernel_552/2667905393.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  NadalNo = data['Match_Winner'].value_counts()[0]+data['Match_Winner'].value_counts()[2]
/tmp/ipykernel_552/2667905393.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  NadalNo = data['Match_Winner'].value_counts()[0]+data['Match_Winner'].value_counts()[2]
/tmp/ipykernel_552/2667905393.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  SinnerNo = data['Match_Winner'].value_counts()[0]+data['Match_Winner'].value_counts()[1]
/tmp/ipykernel_552/2667905393.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  SinnerNo = data['Match_Winner'].value_counts()[0]+data['Match_Winner'].value_counts()[1]

In [116]:
data.head()

status = Nadalyes*hardnadal*overcast_nadal*low_nadal*breezy_nadal*night_nadal*final_nadal*against_nadal
status = Nadalyes*grassnadal*humid_nadal*low_nadal*calm_nadal*day_nadal*favour_nadal*sf_nadal


if status == 0:
  status= "Djovick"
elif status == 1:
  status = "Nadal"
elif status == 2:
  status = "Sinner"

status
pd.DataFrame({"Winner":[status]})

    Winner
0  Djovick